

// Wallet list with images directly used

export interface WalletListI {
    name: string,
    img: string
}
export const walletList: WalletListI[] = [
    { name: "1inch Wallet", img: "/assets/wallets/1inchWallet.png" },
    { name: "Aave", img: "/assets/wallets/aave.png" },
    { name: "Aktionariat", img: "/assets/wallets/aktionariat.jpg" },
    { name: "Alice", img: "/assets/wallets/alice.jpg" },
    { name: "Alpha Wallet", img: "/assets/wallets/alphaWallet.jpg" },
    { name: "Argent", img: "/assets/wallets/argent.jpg" },
    { name: "Atomex", img: "/assets/wallets/atomex.png" },
    { name: "Atomic", img: "/assets/wallets/atomic.jpg" },
    { name: "AT Wallet", img: "/assets/wallets/ATWallet.jpg" },
    { name: "Authereum", img: "/assets/wallets/authereum.jpg" },
    { name: "Binana", img: "/assets/wallets/binana.jpg" },
    { name: "Binance Chain", img: "/assets/wallets/binanceChain.png" },
    { name: "Bitkeep", img: "/assets/wallets/bitkeep.png" },
    { name: "Bitpay", img: "/assets/wallets/bitpay.jpg" },
    { name: "BRD", img: "/assets/wallets/brd.jpg" },
    { name: "Bridge Wallet", img: "/assets/wallets/bridgeWallet.jpg" },
    { name: "Coin98", img: "/assets/wallets/coin98.jpg" },
    { name: "Coinbase", img: "/assets/wallets/coinbase.png" },
    { name: "Coinomi", img: "/assets/wallets/coinmoni.png" },
    { name: "Cosmos Station", img: "/assets/wallets/cosmosStation.png" },
    { name: "Cybavo", img: "/assets/wallets/cybavo.jpg" },
    { name: "Dcent", img: "/assets/wallets/dcent.jpg" },
    { name: "Defi", img: "/assets/wallets/defi.jpg" },
    { name: "Digitex", img: "/assets/wallets/digitex.png" },
    { name: "Dok Wallet", img: "/assets/wallets/dokWallet.jpg" },
    { name: "Easy Pocket", img: "/assets/wallets/easyPocket.jpg" },
    { name: "Ellipal", img: "/assets/wallets/ellipal.jpg" },
    { name: "Exodus Wallet", img: "/assets/wallets/exodusWallet.png" },
    { name: "Flare", img: "/assets/wallets/flare.jpg" },
    { name: "Fortmatic", img: "/assets/wallets/formatic.jpg" },
    { name: "Gnosis Safe", img: "/assets/wallets/gnosisSafe.jpeg" },
    { name: "Grid Plus", img: "/assets/wallets/gridPlus.jpg" },
    { name: "Halo Defi", img: "/assets/wallets/haloDefi.jpg" },
    { name: "Hippowallet", img: "/assets/wallets/hippOwallet.jpg" },
    { name: "Huobi", img: "/assets/wallets/huobi.jpeg" },
    { name: "ImToken", img: "/assets/wallets/imToken.jpg" },
    { name: "Infinito", img: "/assets/wallets/infinito.jpg" },
    { name: "Keyring Pro", img: "/assets/wallets/keyringPro.png" },
    { name: "KyberSwap", img: "/assets/wallets/kyberSwap.jpeg" },
    { name: "Ledger", img: "/assets/wallets/ledger.png" },
    { name: "Ledger Live", img: "/assets/wallets/ledgerLive.png" },
    { name: "Linen", img: "/assets/wallets/linen.jpg" },
    { name: "Loopring", img: "/assets/wallets/loopring.jpeg" },
    { name: "Math Wallet", img: "/assets/wallets/mathWallet.jpg" },
    { name: "MetaMask", img: "/assets/wallets/metaMask.png" },
    { name: "Midas", img: "/assets/wallets/midas.jpg" },
    { name: "Mykey", img: "/assets/wallets/mykey.jpg" },
    { name: "Nash", img: "/assets/wallets/nash.png" },
    { name: "Onto", img: "/assets/wallets/onto.jpg" },
    { name: "OwnBit", img: "/assets/wallets/ownBit.jpg" },
    { name: "PayTube", img: "/assets/wallets/payTube.jpg" },
    { name: "Peak Defi", img: "/assets/wallets/peakdefi.jpg" },
    { name: "Particle Wallet", img: "/assets/wallets/particle.png" },
    { name: "Phantom", img: "/assets/wallets/phantom.jpg" },
    { name: "Pillar", img: "/assets/wallets/pillar.jpg" },
    { name: "Portis", img: "/assets/wallets/portis.png" },
    { name: "Rainbow", img: "/assets/wallets/rainbow.png" },
    { name: "Ronin", img: "/assets/wallets/ronin.png" },
    { name: "RWallet", img: "/assets/wallets/rwallet.jpg" },
    { name: "SafeMoon", img: "/assets/wallets/safeMoon.png" },
    { name: "SafePal", img: "/assets/wallets/safePal.png" },
    { name: "Saitama Wallet", img: "/assets/wallets/saitamaWallet.png" },
    { name: "Spark Point", img: "/assets/wallets/sparkPoint.jpg" },
    { name: "Spatium", img: "/assets/wallets/spatium.jpg" },
    { name: "Sui Wallet", img: "/assets/wallets/sui.png" },
    { name: "Talken", img: "/assets/wallets/talken.jpg" },
    { name: "Terra Station", img: "/assets/wallets/terraStation.png" },
    { name: "Tokenary", img: "/assets/wallets/tokenary.jpg" },
    { name: "Torus", img: "/assets/wallets/torus.jpg" },
    { name: "Tron", img: "/assets/wallets/tron.png" },
    { name: "Trust", img: "/assets/wallets/trust.jpg" },
    { name: "Trust Vault", img: "/assets/wallets/trustVault.jpg" },
    { name: "Unstoppable", img: "/assets/wallets/unstoppable.jpg" },
    { name: "Via Wallet", img: "/assets/wallets/viaWallet.jpg" },
    { name: "Vision", img: "/assets/wallets/vision.jpg" },
    { name: "WalletConnect", img: "/assets/wallets/walletConnet.png" },
    { name: "WallEth", img: "/assets/wallets/wallEth.jpg" },
    { name: "Wallet Io", img: "/assets/wallets/walletIo.jpg" },
    { name: "Zelcore", img: "/assets/wallets/zelcore.jpg" },
  ];


  export const webName = ["BACKEND MAINET"]